name: 04 - Using Actions

on: workflow_dispatch

jobs:
  build:
    defaults:
      run:
        working-directory: 04-using-actions/react-app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
      - name: Install dependencies
        run: npm ci
      - name: Run Unit Tests
        run: npm run test
