name: 13 - Caching

on:
  workflow_dispatch:
    inputs:
      use-cache:
        type: boolean
        description: "Use cache"
        default: true
      node-version:
        type: choice
        description: "Node version"
        options:
          - 18.x
          - 20.x
          - 21.x
        default: 20.x

jobs:
  install-deps:
    defaults:
      run:
        working-directory: 13-caching/react-app
    outputs:
      deps-cache-key: ${{ steps.cache-key.outputs.CACHE_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
      - name: Calculate cache key
        id: cache-key
        run: |
          echo "CACHE_KEY=deps-node-modules-${{ hashFiles('13-caching/react-app/package-lock.json') }}" >> $GITHUB_OUTPUT
      - name: Download cached dependencies
        uses: actions/cache@v4
        id: cache
        if: ${{ inputs.use-cache }}
        with: 
          path: 13-caching/react-app/node_modules
          key: ${{ steps.cache-key.outputs.CACHE_KEY }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
  build:
    defaults:
      run:
        working-directory: 13-caching/react-app
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
      - name: Download cached dependencies
        uses: actions/cache@v4
        id: cache
        if: ${{ inputs.use-cache }}
        with: 
          path: 13-caching/react-app/node_modules
          key: ${{ needs.install-deps.outputs.deps-cache-key }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Testing
        run: npm test
      - name: Bulding
        run: npm run build
      - name: Deploying to prod
        run: echo "Deploying to prod"
