name: 14 - Artifacts

on:
  workflow_dispatch:

jobs:
  test-build:
    defaults:
      run:
        working-directory: 14-artifacts/react-app
    outputs:
      deps-cache-key: ${{ steps.cache-key.outputs.CACHE_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Calculate cache key
        id: cache-key 
        run: |
          echo "CACHE_KEY=deps-node-modules-${{ hashFiles('14-artifacts/react-app/package-lock.json') }}" >> $GITHUB_OUTPUT
      - name: Download cached dependencies
        uses: actions/cache@v4
        id: cache
        with: 
          path: 14-artifacts/react-app/node_modules
          key: ${{ steps.cache-key.outputs.CACHE_KEY }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Unit tests
        run: npm test
      - name: Build code
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: 14-artifacts/react-app/build
  debloy:
    needs: test-build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app
          path: build
      - name: Deploy
        run: echo "Deploying to prod"
      - name: Show folder structure
        run: ls -R
